spring:
  application:
    name: gateway

server:
  port: 8080

np:
  loadbalancer:
    strategy: LEAST_CONNECTIONS
    weights:
      products-service:7cbba038-1182-47cb-ab45-de98e8e77c52: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: false
    fetch-registry: true

logging:
  level:
    com.netflix.eureka: DEBUG