spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


server:
  port: 8080

np:
  loadbalancer:
    strategy: WEIGHTED_ROUND_ROBIN
    weights:
      products-service-0: 1
      products-service-1: 2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: false
    fetch-registry: true

logging:
  level:
    com.netflix.eureka: DEBUG
